sudo: required
services:
  - docker

before_install:
  - docker build -t mikel1994/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikel1994/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "React-docker"
  env: "React-docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-533547490636"
  bucket_path: "React-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

notifications:
  email:
    recipients:
      - p.andrzejewski100@gmail.com
    on_success: always
    on_failure: always
