sudo: required
services:
  - docker

before_install:
  - docker build -t mikel1994/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikel1994/docker-react npm run test

notifications:
  email:
    recipients:
      - p.andrzejewski100@gmail.com
    on_success: always
    on_failure: always
